#!/usr/bin/env python3
import argparse
from mplisp import evaluator


def run(args):
    if not args.eval:
        with open(args.input) as file_object:
            input_value = file_object.read()
    else:
        input_value = args.input

    try:
        result = evaluator.evaluate(input_value, None, args.test)

        for line in result:
            if line is not None:
                print(line)
    except ValueError as e:
        print(e.args[0])


def main():
    parser = argparse.ArgumentParser(description='mplisp interpreter')
    parser.add_argument('input', help='input (file or string)')
    parser.add_argument('-e', '--eval', help='evaluate the input',
                        action='store_true')
    parser.add_argument('-t', '--test', help='run tests ((.*)! functions)',
                        action='store_true')

    run(parser.parse_args())


if __name__ == "__main__":
    main()
